// All 13 Reactive Resume-inspired templates
// Each defines: id, name, style (layout type), accent color, bg, description, and thumbnail colors

export const TEMPLATES = [
  {
    id: 'azurill',
    name: 'Azurill',
    desc: 'Two-column · Soft blue sidebar',
    layout: 'sidebar-left',
    accent: '#4f8ef7',
    sidebar: '#1e3a5f',
    tag: 'Popular',
  },
  {
    id: 'bronzor',
    name: 'Bronzor',
    desc: 'Single-column · Minimal ATS',
    layout: 'single',
    accent: '#b45309',
    sidebar: null,
    tag: 'ATS',
  },
  {
    id: 'chikorita',
    name: 'Chikorita',
    desc: 'Two-column · Fresh green accent',
    layout: 'sidebar-left',
    accent: '#16a34a',
    sidebar: '#14532d',
    tag: 'Fresh',
  },
  {
    id: 'ditto',
    name: 'Ditto',
    desc: 'Single-column · Purple header band',
    layout: 'top-band',
    accent: '#7c3aed',
    sidebar: '#7c3aed',
    tag: 'Bold',
  },
  {
    id: 'gengar',
    name: 'Gengar',
    desc: 'Two-column · Dark sidebar',
    layout: 'sidebar-left',
    accent: '#a855f7',
    sidebar: '#1e1b4b',
    tag: 'Dark',
  },
  {
    id: 'glalie',
    name: 'Glalie',
    desc: 'Single-column · Ice blue lines',
    layout: 'single',
    accent: '#0891b2',
    sidebar: null,
    tag: 'Clean',
  },
  {
    id: 'kakuna',
    name: 'Kakuna',
    desc: 'Two-column · Warm amber sidebar',
    layout: 'sidebar-right',
    accent: '#d97706',
    sidebar: '#78350f',
    tag: 'Warm',
  },
  {
    id: 'lapras',
    name: 'Lapras',
    desc: 'Single-column · Teal header',
    layout: 'top-band',
    accent: '#0d9488',
    sidebar: '#0d9488',
    tag: 'Modern',
  },
  {
    id: 'leafish',
    name: 'Leafish',
    desc: 'Two-column · Emerald sidebar',
    layout: 'sidebar-left',
    accent: '#059669',
    sidebar: '#064e3b',
    tag: 'Nature',
  },
  {
    id: 'onyx',
    name: 'Onyx',
    desc: 'Single-column · Black & white executive',
    layout: 'single',
    accent: '#111111',
    sidebar: null,
    tag: 'Executive',
  },
  {
    id: 'pikachu',
    name: 'Pikachu',
    desc: 'Two-column · Yellow accent sidebar',
    layout: 'sidebar-left',
    accent: '#ca8a04',
    sidebar: '#713f12',
    tag: 'Vibrant',
  },
  {
    id: 'rhyhorn',
    name: 'Rhyhorn',
    desc: 'Single-column · Stone grey classic',
    layout: 'single',
    accent: '#475569',
    sidebar: null,
    tag: 'Classic',
  },
  {
    id: 'ditgar',
    name: 'Ditgar',
    desc: 'Two-column · Rose red sidebar',
    layout: 'sidebar-left',
    accent: '#e11d48',
    sidebar: '#881337',
    tag: 'Bold',
  },
]

export const getTemplate = (id) => TEMPLATES.find(t => t.id === id) || TEMPLATES[0]
